### ISSUE TITLE
What is token in patch_pipe?

### ISSUE THREAD

**Issue by FBehrad** [cloneofsimo/lora#125]
When I get inference according to this [link ](https://github.com/cloneofsimo/lora/blob/master/scripts/run_img2img.ipynb), I face the following error. 
`TypeError: patch_pipe() missing 1 required positional argument: 'token'
`
When I debugged the code, I found patch_pip requires the unet_path and token, both of which are string. The question is that what is the token?

**Comment by cloneofsimo** [comment]
You might want to update LoRA to the latest version. token is optional argument in the latest version
