### ISSUE TITLE
lora_pti:  AttributeError: 'UNet2DConditionModel' object has no attribute 'gradient_checkpointing_enable'

### ISSUE THREAD

**Issue by riccardobl** [cloneofsimo/lora#126]
When running lora_pti with gradient checkpointing enabled, this error is fired
`        AttributeError: 'UNet2DConditionModel' object has no attribute 'gradient_checkpointing_enable'`
at        [ lora_diffusion/cli_lora_pti.pyhttps://github.com/cloneofsimo/lora/blob/master/lora_diffusion/cli_lora_pti.py#L592](https://github.com/cloneofsimo/lora/blob/master/lora_diffusion/cli_lora_pti.py#L592)

It seems the correct method name for the UNet2DConditionModel object should be  `enable_gradient_checkpointing()` and not `gradient_checkpointing_enable()`, replacing `unet.gradient_checkpointing_enable()` with `unet.enable_gradient_checkpointing()` indeed seems to solve the issue

**Comment by cloneofsimo** [comment]
I've never used that option, must be the reason why the bug is here. Thank you so much!

**Comment by cloneofsimo** [comment]
#130 Done!
