### ISSUE TITLE
CLIPTextEncoder loads in float32 when using revision="fp16"

### ISSUE THREAD

**Issue by ethansmith2000** [cloneofsimo/lora#131]
<img width="685" alt="Screen Shot 2023-01-09 at 9 12 36 PM" src="https://user-images.githubusercontent.com/98723285/211446295-9b176aa6-de47-4385-b555-eba3deef7072.png">

probably not a big issue if all's been running fine, but noticed for some reason the text model loads in at torch.float32 when using 
_revision = "fp16"_

just wanted to share as i had recently dealt with an issue on a separate project where accelerator hadn't been properly doing mixed precision for me.

**Comment by cloneofsimo** [comment]
Ha, interesting. Thank you!

**Comment by cloneofsimo** [comment]
I guess this is a bug from Huggingface side?

**Comment by brian6091** [comment]
That's weird. If you look at the binary files on https://huggingface.co/runwayml/stable-diffusion-v1-5/tree/fp16/text_encoder,
you see that they are smaller than the main revision.

Actually, I just tried this and I got:

> print(pipe.text_encoder.dtype)
> torch.float16

I'm guessing you may have tried the main revision, and then switched to fp16, and the cache didn't update?

**Comment by ethansmith2000** [comment]
Yeah that is odd, might just be me haha. I now do .from_pretrained( revision="fp16", torch_dtype=torch.float16) just to be double sure, which seems to work okay lol.

iirc main and fp16 revision should be more/less the same values so loading in the main revision then doing .to(torch.float32) i think should end up being the same
