### ISSUE TITLE
ImportError: cannot import name 'CLIPTextModelWithProjection' from 'transformers'

### ISSUE THREAD

**Issue by GongXinyuu** [cloneofsimo/lora#134]
Hello, thanks for your great work!

However, I met such an error when I tried to ```from lora_diffusion import patch_pipe, tune_lora_scale```.

The error message is ```ImportError: cannot import name 'CLIPTextModelWithProjection' from 'transformers'```. Coudl you help to check on this? Thanks.

**Comment by ethansmith2000** [comment]
CLIPTextModelWithProjection is one of the newest additions to the Transformers library, I've typically had that issue when using a version that is <4.25.1

**Comment by cloneofsimo** [comment]
Awesome.
