### ISSUE TITLE
[FR]CLI to convert lora safetensors created by WebUI into standard format

### ISSUE THREAD

**Issue by wsxiaoys** [cloneofsimo/lora#141]
Example file:
https://huggingface.co/YoungMasterFromSect/Trauter_LoRAs/tree/main/LoRA/Fate-Grand-Order/Minamoto-no-Raikou

These files are created with WebUI plugin thus doesn't come with metadata attached. A converting utility will be handful.

**Comment by wsxiaoys** [comment]
this seems to be a bug for trauter's lora model. close for now: https://huggingface.co/YoungMasterFromSect/Trauter_LoRAs/discussions/3

**Comment by brian6091** [comment]
Could probably get away without metadata if the keys have the full path to the patched module.

**Comment by JamesSand** [comment]
Actually, the difference between webui format safetensor and format of safetensor supported by this repo is that there keys for lora is completely different. Is there any of matching this two kinds of keys together?
