### ISSUE TITLE
Differences in implementations of UNET_DEFAULT_TARGET_REPLACE

### ISSUE THREAD

**Issue by thojmr** [cloneofsimo/lora#146]
Hey there. 

I noticed that this project sets Unet filters to
https://github.com/cloneofsimo/lora/blob/e19f6ae22c3fa4d6da252c5b7443fc0942088cd7/lora_diffusion/lora.py#L53

while Kohya's implementation sets
```
UNET_TARGET_REPLACE_MODULE = ["Transformer2DModel", "Attention"]
```
https://github.com/kohya-ss/sd-scripts/blob/cae42728aba035a7ac305a40c75954530c3c3444/networks/lora.py#L55

The `Attention` module is the only one in common.  Wouldn't this produce very different results for a model trained on each repo?
Just wondering why the difference exists in the first place?

**Comment by brian6091** [comment]
Boils down to a difference in how each author chose to search for modules to add LoRA to in the unet. @cloneofsimo 's initial implementation followed the original LoRA paper in sticking with the linear layers in the attention modules ("CrossAttention"), and he added one of the feedfoward layers later, hence the additional "GEGLU" default. Both the attention and ff are part of a larger transformer block, which is the level at which @kohya-ss starts his search.  Both versions will apply LoRA to the self- and cross-attention. The one difference is that LoRA will be applied to an additional ff layer in @kohya-ss 's search, which adds more parameters to train that may or may not make a difference.

That said, if you want that extra ff layer, you can just replace the default search with `{"Transformer2DModel"}` in @cloneofsimo 's (pass argument when you call the function [here](https://github.com/cloneofsimo/lora/blob/master/lora_diffusion/lora.py#L139). Removing the extra ff layer from @kohya-ss 's version requires editing the class definition.

Funnily enough, the one common search term "Attention" can actually be removed, as there is no class named "Attention" in the unet.

**Comment by thojmr** [comment]
Thanks for the explanation.  
I did end up training Kohya's with `["CrossAttention", "Attention", "GEGLU"]` and got somewhat similar results compared with `["Transformer2DModel", "Attention"]`.  But it's always difficult to properly compare txt2img results. So I'm content to leave it as is.
