### ISSUE TITLE
`OrderedDict mutated during iteration` during inference

### ISSUE THREAD

**Issue by JunMa11** [cloneofsimo/lora#15]
Hi @cloneofsimo ,

Thanks for sharing the great repo.

I got the following runtime error when changing the checkpoint. 

It can be solved by restarting the Jupiter notebook. Why can't I run the same cell twice with the same code?

```python
from lora_diffusion import monkeypatch_lora, tune_lora_scale

monkeypatch_lora(pipe.unet, torch.load("../lora_weight_e3499_s17500.pt"))
tune_lora_scale(pipe.unet, 1.00)

torch.manual_seed(1)
image = pipe(prompt, num_inference_steps=50, guidance_scale=7).images[0]
# image.save("../contents/disney_lora.jpg")
image

```

```python

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
/tmp/ipykernel_3708385/3204262117.py in <module>
      1 checkpoint = torch.load("..//output_example/lora_weight_e3499_s17500.pt")
----> 2 monkeypatch_lora(pipe.unet, checkpoint)
      3 tune_lora_scale(pipe.unet, 1.00)
      4 
      5 torch.manual_seed(1)

~/Documents/I2I/lora/lora_diffusion/lora.py in monkeypatch_lora(model, loras, target_replace_module)
    130     for _module in model.modules():
    131         if _module.__class__.__name__ in target_replace_module:
--> 132             for name, _child_module in _module.named_modules():
    133                 if _child_module.__class__.__name__ == "Linear":
    134 

~/anaconda3/envs/lora/lib/python3.9/site-packages/torch/nn/modules/module.py in named_modules(self, memo, prefix, remove_duplicate)
   1879                 memo.add(self)
   1880             yield prefix, self
-> 1881             for name, module in self._modules.items():
   1882                 if module is None:
   1883                     continue

RuntimeError: OrderedDict mutated during iteration

```

**Comment by cloneofsimo** [comment]
I'm really not sure why, I would guess it's because im monkey patching, and it messes up with other pytorch implementations...

**Comment by JunMa11** [comment]
Thanks for your reply very much. I think so since the stablediffusion pipeline works well in the same jupyter notebook when run the same cell multiple times. Do you have any suggestions to fix the monkey patching?

```python
model_id = "stabilityai/stable-diffusion-2-1-base"

pipe = StableDiffusionPipeline.from_pretrained(model_id, torch_dtype=torch.float16).to(
    "cuda"
)

prompt = "style of sky, lion"
# torch.manual_seed(43)
image = pipe(prompt, num_inference_steps=50, guidance_scale=7).images[0]
```

**Comment by cloneofsimo** [comment]
Yeah, we have another option : `weight_apply_lora`, which alternates Unet's weight indefinitely. This disables you from `tune_lora_scale`, but it is simply native unet, so doesn't do anything to the model except for changing the weights. I didn't add this to readme because it was used as part of CLI.

**Comment by cloneofsimo** [comment]
i.e., applys :

$$
W \leftarrow W + \alpha AB^T
$$

**Comment by JunMa11** [comment]
Thanks for your guidance very much:)

**Comment by brian6091** [comment]
The error happens when trying to monkeypatch a pipeline that has already been monkeypatched. One workaround is to just create a new pipeline again. Takes a few seconds, and at least you don't have to restart the notebook.
