### ISSUE TITLE
Import error in release v0.1.2

### ISSUE THREAD

**Issue by tripathiarpan20** [cloneofsimo/lora#153]
Hi! Thanks for the amazing repo @cloneofsimo !!

For the release 0.1.2 the following error pops up on Colab by pip installing from the v0.1.2 commit:  
![image](https://user-images.githubusercontent.com/42506819/215353194-9355ef47-0da4-4744-95b7-0a51b9362c38.png) 

Verified the above issue by retrying from release v0.1.1, which imports successfully.

**Comment by cloneofsimo** [comment]
Ah yes, monkeypatch_lora is depreciated. Use patch_pipe instead. I think the colab is outdated.

**Comment by tripathiarpan20** [comment]
Yeah that solved it, thanks!
