### ISSUE TITLE
Few issues on the latest release (xformers/mediapipe)

### ISSUE THREAD

**Issue by cian0** [cloneofsimo/lora#159]
Just want to open here 2 new issues we've encountered on Discord:

1/ Mediapipe where it says the image doesnt have 3 channel RGB
2/ xformers not working

Solutions:
1/ 
changing:
[Image.open(f) for f in self.instance_images_path]

to :
[Image.open(f).convert('RGB') for f in self.instance_images_path]
(in around line 188 i think, dataset.py)

2/ Downgrade to xformers 0.0.14.dev0
thru: pip install https://github.com/Zuxier/xformers/releases/download/torch1.13-0.14dev0-python3.10/xformers-0.0.14.dev0-cp310-cp310-linux_x86_64.whl

**Comment by brian6091** [comment]
@cian0 what is the problem with xformers? It just errors out?
I'm using the latest RC on pip, which seems to work fine:

pip install xformers==0.0.16rc425

**Comment by cian0** [comment]
> @cian0 what is the problem with xformers? It just errors out? I'm using the latest RC on pip, which seems to work fine:
> 
> pip install xformers==0.0.16rc425

wait, I think my issue actually was I didn't uninstall the old lora_diffusion cli before upgrading, so closing this unless there are other ones experiencing the same
