### ISSUE TITLE
Training textencoder

### ISSUE THREAD

**Issue by kenborge** [cloneofsimo/lora#16]
Currently only the Unet is trained with lora, but especially with dreambooth it's most common to also train the text encoder at the same time as it gives vastly better results . Is it possible to also apply the lora method to the textencoder to get the same benefits there?

**Comment by Thomas-MMJ** [comment]
It is already an option

just add "--train_text_encoder"

**Comment by kenborge** [comment]
@Thomas-MMJ you can't use it right now, as it doesn't save the weights just the lora unet weights. Enabling it will just give you a unet that isn't compatible with the textencoder you actually use for inference later. 

This can be fixed by just saving the textencoding weights though. But my question is also about using lora on the textencoder not just training it as normal.

**Comment by brian6091** [comment]
Looks like the trained pipeline is generated, one needs to just add

`pipeline.save_pretrained(SOME_DIRECTORY)
`
where the lora weights are saved

**Comment by cloneofsimo** [comment]
Nice idea! @kenborge , although I do have a concern that it will further complicate things because that way you need *two* lora per model... But with bit of thinking I think we can pull this off. I'll work on this after my exam though 😄

**Comment by cloneofsimo** [comment]
@brian6091 Yeah you are right! but that will save the entire model for the CLIP Encoder, so it will be pretty large (but not large as Unet though)

**Comment by brian6091** [comment]
If space is an issue, one could always save just the text encoder, and use it for building the pipeline after

**Comment by cloneofsimo** [comment]
Now this is possible!
