### ISSUE TITLE
Config.json not found

### ISSUE THREAD

**Issue by digitalimmortalis** [cloneofsimo/lora#2]
I got this error:

`EntryNotFoundError(f"404 Client Error: Entry Not Found for url: {response.url}")
transformers.utils.hub.EntryNotFoundError: 404 Client Error: Entry Not Found for url: https://huggingface.co/stabilityai/stable-diffusion-2-1-base/resolve/main/config.json
`

I have manually confirmed that the config.json file doesn't exist in the HuggingFace website.

My launch code

`!accelerate launch lora/train_lora_dreambooth.py \
  --pretrained_model_name_or_path="stabilityai/stable-diffusion-2-1-base"  \
  --instance_data_dir="/kaggle/input/xxxx" \
  --class_data_dir="/kaggle/input/class" \
  --output_dir="/kaggle/working/checkpoints" \
  --instance_prompt="a photo of xxxx" \
  --class_prompt="a photo of nnnnn" \
  --resolution=512 \
  --train_batch_size=1 \
  --gradient_accumulation_steps=1 \
  --learning_rate=1e-4 \
  --lr_scheduler="constant" \
  --lr_warmup_steps=0 \
  --save_steps=2000 \
  --max_train_steps=10000`

I would like to know how to solve this. Thx.

**Comment by osi1880vr** [comment]
as far as I understand it needs to be a diffuser model which in the prcess gets that config.json. I ran one of the scripts here to migrate the ckpt into a diffusion model, https://github.com/huggingface/diffusers/tree/main/scripts. that created a whole bunch of files and folders as well as that json file....

**Comment by digitalimmortalis** [comment]
I resolve this by simply git clone the runwayml/stable-diffusion-v1-5 repo.

**Comment by osi1880vr** [comment]
I did resolve it by converting a ckpt to a diffuser model

 

Von: digitalimmortalis ***@***.***> 
Gesendet: Dienstag, 13. Dezember 2022 23:29
An: cloneofsimo/lora ***@***.***>
Cc: osi1880vr ***@***.***>; Comment ***@***.***>
Betreff: Re: [cloneofsimo/lora] Config.json not found (Issue #2)

 

I resolve this by simply git clone the runwayml/stable-diffusion-v1-5 repo.
