### ISSUE TITLE
Preview while training

### ISSUE THREAD

**Issue by scarbain** [cloneofsimo/lora#21]
Hi ! Thank you very much for this implementation !

I'm able to train with higher batch than dreambooth so that's great.

Do you have an easy solution to get a preview of generated images while training to check if it's going well and not overfitting ?

**Comment by cloneofsimo** [comment]
Ah, thats currently not supported... sorry..

**Comment by cloneofsimo** [comment]
You can check this out! : https://github.com/cloneofsimo/lora/blob/master/scripts/lora_training_process_visualized.ipynb
