### ISSUE TITLE
Converting to CKPT format for A1111's repo

### ISSUE THREAD

**Issue by alexfredo** [cloneofsimo/lora#23]
Hi I have generate a lora_weight.pt file on Hugging Face using this https://huggingface.co/spaces/ysharma/Low-rank-Adaptation
Im a noobs how I convert this file into a checkpoint ? please helps thanks

**Comment by cloneofsimo** [comment]
If you still want it, use the CLIs to convert .pt files into ckpt file

**Comment by behinger** [comment]
Unfortunately, both suggestions didnt work for me.
1) Automatic throws this error if I add it to embeddings
```
Exception: Couldn't identify lora_weight.pt as neither textual inversion embedding nor diffuser concept.  
```
2) It is unclear to me, whether the cli tool also applies the re-trained text encoder? In any case, I only get brown-pixel mess as output if I load a ckpt file with both trained e.g. in automatic.

**Comment by cobanov** [comment]
You can add --test-lora to your COMMANDLINE_ARGS= in your webui-user.bat/sh to enable the new LORA option in the Advanced section, under Tuning

**Comment by behinger** [comment]
thanks, will try. For others stumbling over this: You will need the `dreambooth` extension in `automatic!!!!`

**Comment by satwiksunnam19** [comment]
Hey @behinger @cobanov @cloneofsimo both the above methods have described thrown errors
1. directly placing .pt file in the embeddings folder, I got this error "there are no embeddings in the provided .pt file"
2. When I tried to use this repo for training a dreambooth with LORA, the weights have saved in the.safetensors format and when i tried the method which is described in readme file "$ lora_add runwayml/stable-diffusion-v1-5 path_to_my_safetensors ./output_merged.ckpt 0.7 --mode upl-ckpt-v2"
it threw an error "RuntimeError: stack expects a non-empty TensorList"
3. when i tried the "$ lora_add runwayml/stable-diffusion-v1-5 path_to_my.pt file ./output_merged.ckpt 0.7 --mode upl-ckpt-v2"it threw an error of "AttributeError: 'NoneType' object has no attribute 'keys'".

Hope you'll provide a guide on how to solve this problem, @cloneofsimo ASAP.
Thanks & Regards,
Satwik Sunnam.

**Comment by tengshaofeng** [comment]
@behinger @alexfredo @cobanov @satwiksunnam19 .  Now you can use the small lora weight to WebUi.I have add some code to support the Automatic111 WebUI. What you should do is just runing 'train_lora_dreambooth.py', then you will find that there is another lora_weight_webui.safetensors in the output dir. That is the right weight for WebUI.
reference my project in https://github.com/tengshaofeng/lora_tbq

**Comment by oscarnevarezleal** [comment]
awesome @tengshaofeng, can you explain what exactly does your change?

**Comment by tengshaofeng** [comment]
@oscarnevarezleal Saving weights according to the format which needed by Automatic111 WebUI.
