### ISSUE TITLE
There are some problems when I run the scripts/run_img2img.ipynb

### ISSUE THREAD

**Issue by AFeng-x** [cloneofsimo/lora#238]
Does anybody have the same problem as me? I haven't change any code.
File "path/lora_diffusion/lora.py", line 55, in forward
self.linear(input)
RuntimeError: The size of tensor a (320) must match the size of tensor b (2560) at non-singleton dimension 2

**Comment by Lucky-Light-Sun** [comment]
> 
just degrade you diffusers version, using this command:
`pip3 install diffusers==0.14`
