### ISSUE TITLE
Citation

### ISSUE THREAD

**Issue by FelixDeMan** [cloneofsimo/lora#247]
Hi!

Love your work, been toying around with it a lot! 

I will include some experiments in my Msc. Thesis, how can I cite your work?

Cheers!

**Comment by cloneofsimo** [comment]
Hey there, thank you for your considerations. There are now quite a lot of work based on this repo, and most of them dont cite my work so I appreciate that a lot.

```bibtex
@misc{lora_stable, 
 title={Low-rank Adaptation for Fast Text-to-Image Diffusion Fine-tuning}, 
 author={Simo Ryu},
 howpublished={\url{[https://github.com/cloneofsimo/lora}](https://github.com/cloneofsimo/lora%7D)}, 
 publisher = {GitHub},
 journal = {GitHub repository}
}
```

This format would be good enough imo. Again, thank you

**Comment by FelixDeMan** [comment]
Hi,


Sorry to hear your work goes uncited! You deserve all the credits. I fixed the formatting for you:
```
@misc{lora_stable, 
 title={Low-rank Adaptation for Fast Text-to-Image Diffusion Fine-tuning}, 
 author={Simo Ryu},
 howpublished={\url{https://github.com/cloneofsimo/lora}}, 
 publisher = {GitHub},
 journal = {GitHub repository}
}
```

Thank you so much! Perhaps you could add this to the side panel of the repo!
