### ISSUE TITLE
How to "patch" diffusers model with lora values, save as checkpoint?

### ISSUE THREAD

**Issue by d8ahazard** [cloneofsimo/lora#3]
I know it'd probably be more efficient to just save the .pt file, but is there some way I could apply the data from lora training back to a regular diffusers model and then save it as a ckpt?

**Comment by cloneofsimo** [comment]
Yes! checkout cli merging lora with unet.

**Comment by d8ahazard** [comment]
Thanks, figured that out. Now, is there a simple way to "resume" training with an existing .pt file? :D
