### ISSUE TITLE
Change to or include Apache2 license

### ISSUE THREAD

**Issue by timh** [cloneofsimo/lora#30]
See #12

Just an FYI:
To stay completely legit, you should license this repo as Apache2 -OR- at include the Apache2 license in the repo. This is because train_lora_dreambooth.py is a derivative work of https://github.com/huggingface/diffusers, which is licensed Apache2. Source with an apache2 license requires distributing a copy of that license.

Moving from MIT to Apache2 doesn't change your rights, or any downstream users of this repo. Commercial use, etc, are still allowed. The only thing that changes is a requirement to distribute a copy of that license.

**Comment by cloneofsimo** [comment]
Thanks! Gotit. I wasnt aware of that 🤣
Just a quick question: would it be possible to make the `train_lora_dreambooth.py` to only apache2 license?
