### ISSUE TITLE
Text encoder still not working correctly with LoRa Dreambooth training script

### ISSUE THREAD

**Issue by JohnnyRacer** [cloneofsimo/lora#31]
Hello, I am getting much better results using the `--train_text_encoder` flag with the Dreambooth script. However, the actual outputed LoRa `.pt` files from models trained with `train_text_encoder` gives very bad results after using monkeypatch to generate images. I suspect that the text encoder's weights are still not saved properly. I tried to save the pipeline directly after each epoch from within the training script, but loading it using `diffusers` gives me strange errors about `torch` not being able to parse the linear layers.  Does anyone have similar experiences with training the text encoder or have any idea why this is happening?

Images sampled from within the training loop (train_text_encoder enabled) :
![2](https://user-images.githubusercontent.com/77214388/207443071-3a7755a7-1d39-4224-9465-159e6eea1e10.png)
![2e](https://user-images.githubusercontent.com/77214388/207443078-41df72f1-8bd3-48d6-b3b4-dc89e9a2fca1.png)
![3](https://user-images.githubusercontent.com/77214388/207443086-61a24648-2b59-45f8-9cb6-a023bd820405.png)

Images sampled after model was monkeypatch with the trained LoRa weights (train_text_encoder enabled) :
![bad1](https://user-images.githubusercontent.com/77214388/207443649-3e352f9c-51a1-4c79-9f36-1d33f0862397.png)
![bad2](https://user-images.githubusercontent.com/77214388/207443737-4ed213b3-c073-44cb-b796-e3202b8fb847.png)
![bad3](https://user-images.githubusercontent.com/77214388/207443750-7e4e2809-d3fd-4818-a174-31d43ae7b15e.png)

The images doesn't seem to correlate with the samples generated while training and has very little cohesiveness with the training images used.

**Comment by cloneofsimo** [comment]
Did you also patch the text encoder as well?

**Comment by cloneofsimo** [comment]
Have a look at:  https://github.com/cloneofsimo/lora/blob/master/scripts/run_with_text_lora_also.ipynb

**Comment by JohnnyRacer** [comment]
> Did you also patch the text encoder as well?

@cloneofsimo 

I'm not sure on how to do that, there is only one `.pt` file that is for the UNet after I am done training. In the notebook there seems to be a seperate `.pt` for the text encoder as well that makes it possible to patch the text encoder.

**Comment by JohnnyRacer** [comment]
@cloneofsimo 
Got the text encoder patching to work , but it seems like it overfits very easily and gives quite bad results at times compared to training Dreambooth without LoRa. And even stranger is that there are a lot more artifacts after using the text encoder patch like watermarks from the training images that are showing up that had not appeared in the training like the examples I had show earlier like the examples below. Any clue why this is occuring?
![overfit](https://user-images.githubusercontent.com/77214388/207488447-318dbdf2-494f-479b-bb66-b559e1298ec7.png)
![overfit1](https://user-images.githubusercontent.com/77214388/207488452-99b29192-f3ec-47cb-bd41-09f676bf22f8.png)

**Comment by cloneofsimo** [comment]
Nice to see that it works. I've found that when it overfits, tuning down both unet and text encoder helps, but with different scale. Also try learning it with prior preservation. Seems like you are dreamboothing with faces, and guide like https://github.com/nitrosocke/dreambooth-training-guide from @nitrosocke might help. (Also says to crop out any artifacts)

**Comment by cloneofsimo** [comment]
https://github.com/cloneofsimo/lora#what-happens-to-text-encoder-lora-and-unet-lora Have a look at this part as well

**Comment by brian6091** [comment]
I've posted some images of the effect of tuning both the unet and the text encoder (with prior preservation) in the discussions section:

https://github.com/cloneofsimo/lora/discussions/37

**Comment by JohnnyRacer** [comment]
> I've posted some images of the effect of tuning both the unet and the text encoder (with prior preservation) in the discussions section:
> 
> #37

Thanks for the amazing guide @brian6091 ! Have you experimented with using a class dataset to act as a regularization similar to what was mentioned in the original Dreambooth paper? I tried to use it but it gives me strange errors about `accelerate.launch()` not being instantiated. I think it could give a noticeable increase image quality compared to using pipeline itself to automatically generate class images.

**Comment by JohnnyRacer** [comment]
> Nice to see that it works. I've found that when it overfits, tuning down both unet and text encoder helps, but with different scale. Also try learning it with prior preservation. Seems like you are dreamboothing with faces, and guide like https://github.com/nitrosocke/dreambooth-training-guide from @nitrosocke might help. (Also says to crop out any artifacts)

From my experience so far it seems like training with LoRA requires much cleaner and specific datasets to work (i.e. aligned faces) , trying to train on more diverse datasets (i.e. pictures of a person in different poses) often leads to bad results.

**Comment by brian6091** [comment]
> > I've posted some images of the effect of tuning both the unet and the text encoder (with prior preservation) in the discussions section:
> > #37
> 
> Thanks for the amazing guide @brian6091 ! Have you experimented with using a class dataset to act as a regularization similar to what was mentioned in the original Dreambooth paper? I tried to use it but it gives me strange errors about `accelerate.launch()` not being instantiated. I think it could give a noticeable increase image quality compared to using pipeline itself to automatically generate class images.

I used a class dataset for the training I showed in the discussion post. It was the same for both Dreambooth and LoRA. I used the SD pipeline to generate the class images. I didn't get time to show the effects of both Dreambooth and LoRA on the class, but I may add some to a future discussion.

I was under the impression that the Dreambooth method was to use SD to generate class images. What did you do to get the error? If you post the error, maybe we could help debug it.

**Comment by JohnnyRacer** [comment]
@brian6091 

I am getting this error if I pass in a directory with `--class_data_dir` : `ValueError: Please make sure to properly initialize your accelerator via `accelerator = Accelerator()` before using any functionality from the `accelerate` library.` Without adding this argument it trains fine.  I've tried using both `accelerate launch` as well as just using `python` to start the script but it gives the same errors. This is on the latest commit to the repo from today. Any ideas on why this is happening?

**Comment by brian6091** [comment]
@JohnnyRacer 
Are you running in Colab? Which script or notebook are you using. I think I've seen this kind of error when there is a malformed input.

**Comment by JohnnyRacer** [comment]
@brian6091 

No I'm running it locally. I am using the `train_lora_dreambooth.py` script from this repo with no modifications. The `./aradesh_train_col` is where I have my training images and `./aradesh_reg_col` is where the regularization images are located. 

The command below works 
```
 accelerate launch train_lora_dreambooth.py \
  --pretrained_model_name_or_path="../sd-v1-5-diffusers" \
  --instance_data_dir="./aradesh_train_col" \
  --output_dir="./aradesh-sd1.5-textenc" \
  --instance_prompt="sks aradesh" \
  --resolution=512 \
  --train_batch_size=1 \
  --gradient_accumulation_steps=1 \
  --learning_rate=1e-4 \
  --lr_scheduler="constant" \
  --lr_warmup_steps=0 \
  --max_train_steps=600 \
  --use_8bit_adam \
  --train_text_encoder
```
The command below doesn't work and gives the `accelerate launch` error that I mentioned earlier.
```
 accelerate launch train_lora_dreambooth.py \
  --pretrained_model_name_or_path="../sd-v1-5-diffusers" \
  --instance_data_dir="./aradesh_train_col" \
  --class_data_dir="./aradesh_reg_col" \
  --output_dir="./aradesh-sd1.5-textenc" \
  --instance_prompt="sks aradesh" \
  --resolution=512 \
  --train_batch_size=1 \
  --gradient_accumulation_steps=1 \
  --learning_rate=1e-4 \
  --lr_scheduler="constant" \
  --lr_warmup_steps=0 \
  --max_train_steps=600 \
  --use_8bit_adam \
  --train_text_encoder
```

**Comment by brian6091** [comment]
I think adding this flag would work:

--with_prior_preservation

I would also add this:

--prior_loss_weight=1.0

since the default weight is oddly huge

**Comment by JohnnyRacer** [comment]
@brian6091 

Also it seems like using the `class_prompt` argument made the VRAM usage increase about 50% (from ~12gb  to 18gb), is this to be expected?

**Comment by brian6091** [comment]
So the class prompt should represent the class you don't want your model to forget. For example, if you are training for a specific person,

instance_prompt = "raretoken person"
class prompt = "person"

I've never trained without prior preservation, so I don't know about the memory increase. If you are running into memory limitations, have a look at the table in the readme here: https://github.com/ShivamShrirao/diffusers/tree/main/examples/dreambooth#readme

**Comment by JohnnyRacer** [comment]
@brian6091 

Ah okay, I was using the same prompt for both earlier and I wasn't getting much of a difference. Is it possible to use gradient checkpointing now for training to reduce VRAM? In an earlier issue I saw that that it was not saving properly.

**Comment by brian6091** [comment]
Ah sorry, I forgot about that. I don't think gradient checkpointing is working yet (if you want to train the text encoder).

**Comment by G-force78** [comment]
What is a good way to check if the results have been trained with good (enough) parameters? So far the likeness is hit and miss, usually miss, thats on 5 images at 5000 steps.

**Comment by brian6091** [comment]
You can sample a few prompts at intermediate checkpoints, say, every 500 or 1000 iterations. You can also track the loss, although that is very noisy.

**Comment by G-force78** [comment]
Ah right I see, just change the path here? monkeypatch_lora(pipe.unet, torch.load(os.path.join(OUTPUT_DIR, "lora_weight.pt")))

**Comment by brian6091** [comment]
@G-force78 
Not sure, depends on what you're using to run the training. But basically, around the part where you save a checkpoint, you need to:
1) construct an inference pipeline
2) monkeypatch it with your weights
3) generate some images

Example here: https://github.com/brian6091/Dreambooth/blob/main/train.py#L934-1006

**Comment by JohnnyRacer** [comment]
@brian6091  Just a quick thought on improving the image quality, I was wondering if there's a way to use generated text captions to enhance the training of the text encoder similar to how embeddings are trained for Automatic1111's repo. The majority of the trained models seem to have a hard time focusing on generating the detail that's desired and is a lot more susceptible to picking up unwanted details,  by conditioning the text model on specific prompts that are matched with the image it should be better at generating more favorable samples.

**Comment by G-force78** [comment]
> @G-force78 Not sure, depends on what you're using to run the training. But basically, around the part where you save a checkpoint, you need to:
> 
>     1. construct an inference pipeline
> 
>     2. monkeypatch it with your weights
> 
>     3. generate some images
> 
> 
> Example here: https://github.com/brian6091/Dreambooth/blob/main/train.py#L934-1006

Im just using the collab

```
#@title LOADING MODEL AND MONKEY PATCHING IT
import torch
from lora_diffusion import monkeypatch_lora, tune_lora_scale
from diffusers import StableDiffusionPipeline


pipe = StableDiffusionPipeline.from_pretrained(PRETRAINED_MODEL, torch_dtype=torch.float16).to("cuda")
monkeypatch_lora(pipe.unet, torch.load(os.path.join(OUTPUT_DIR, "lora_weight.pt")))
monkeypatch_lora(pipe.text_encoder, torch.load(os.path.join(OUTPUT_DIR, "lora_weight.text_encoder.pt")), target_replace_module=["CLIPAttention"])
```

**Comment by JohnnyRacer** [comment]
> 

@G-force78 

Are you having problems or is something not working? That is the correct way to run it.

**Comment by brian6091** [comment]
@G-force78 

Looks right, now just run the pipe with a prompt

**Comment by G-force78** [comment]
> > 
> 
> @G-force78
> 
> Are you having problems or is something not working? That is the correct way to run it.

I think Ive maybe chosen a used token within the sd 2.1 base model or something as the images are nothing like my training images..5000 training steps, 5 images, prompt bobo
![bobotest](https://user-images.githubusercontent.com/114336644/208239573-541c35fa-0a07-4e1e-9b4e-b334840dbb38.png)

Training images example Bob Odenkirk


![800px-Bob_Odenkirk_by_Gage_Skidmore_2](https://user-images.githubusercontent.com/114336644/208239594-efcaefc0-f7bc-4ea8-b42f-1622b2235040.jpg)
