### ISSUE TITLE
Just curious why the license was changed from MIT?

### ISSUE THREAD

**Issue by 2kpr** [cloneofsimo/lora#33]
Just wanted to see why the license was changed to Apache 2.0 from MIT, a particular reason?

For anyone wondering, all code/commits prior to this license change are still licensed under MIT, just wanted to let anyone know that fancies MIT over Apache 2.0.

And if I'm not mistaken (I've heard this from a few people) all current code contributors needed to agree on the license change, or remove the contributed code?

It's not really that big of a deal to me personally, but I'm just curious overall.

**Comment by cloneofsimo** [comment]
Thanks from kind notice from #30 , realized that apache 2 was the needed license.

**Comment by cloneofsimo** [comment]
I also don't know a thing about licensing... so I just did what looked safe

**Comment by 2kpr** [comment]
Ahh, makes sense, didn't know about the derivative work!

Cool, I was just curious after all :)
