### ISSUE TITLE
works but could use guidance

### ISSUE THREAD

**Issue by Thomas-MMJ** [cloneofsimo/lora#5]
I seem to be one of the few to get it working

here are some thoughts and issues

1) might require bleeding edge diffusers and transformers and accelerate - i always have them as current git head, others are probably using older or much older versions.
2) for working on 6GB requires xformers and bnb
3) I had to downgrade xformers due to latest having intermittent incompatibility (xformers cutlass backward isn't compatible with 30xx GPUs and maybe not 40xx GPUs, but it defaults to it sometimes to cutlass in current xformers for memory efficient attention)
4) the learning rate has to be massively higher than expected (1e-4 !!!!) people are used to learning rates of 1e-6 or so and it learns essentially nothing.
5) people don't understand what LORA is doing, might want to provide a brief explanation of why it can do dreambooth with such a small file difference.

Perhaps do a 1.4 example also since people are more familiar with it than 2.1.

You might want to do a tweaked example showing the corgi working (what I posted on reddit works, but isn't very good)

https://huggingface.co/docs/diffusers/training/dreambooth

https://drive.google.com/drive/folders/1BO_dyz-p65qhBRRMRA4TbZ8qW4rB99JZ

You might want to have the end of the example turn it into a .ckpt file so people get something they are used to using.

Also I'd recommend an example trained on a person.

**Comment by cloneofsimo** [comment]
Thanks for the feedback! Changing to ckpt is now available, with `--mode upl-ckpt-v2` 
4d423361de63a1cda84ac3de7a3bd603306159ad 

I'll work on nice guidance on full trainings in the future.

**Comment by Thomas-MMJ** [comment]
Great, will go ahead and close the issue.
