### ISSUE TITLE
Need some small explanations if possible, unet, text encoder, how to use with existing model - for course on stable diffusion 

### ISSUE THREAD

**Issue by FurkanGozukara** [cloneofsimo/lora#68]
Hello. I am working on a full course for stable diffusion. Of course I should also make a lecture for Lora

Can you explain to me
unet vs text encoder?
they produce same file output? 
what is the difference?
difference between Lora and dreambooth?

so dreambooth modifies the trained model weights and assign them to the new prompt you generated. What does lora do?

and the most important part perhaps

will lora be available on automatic11111 web-ui? my lecture will be centered on that
also lets say someone generated unet and text encoder. they produce different outputs right? so how they can use them in web ui? 

by the way this is my first tutorial video with dreambooth : https://www.youtube.com/watch?v=mnCY8uM7E50

[![image](https://user-images.githubusercontent.com/19240467/208475654-9902392b-6140-4246-9ee0-40f513a905e4.png)](https://www.youtube.com/watch?v=mnCY8uM7E50)

**Comment by amerkay** [comment]
Maybe you need to read a few basic things before writing a course. 

Start here https://huggingface.co/blog/stable_diffusion

---

> will lora be available on automatic11111 web-ui? my lecture will be centered on that

See main [README to convert to CKPT](https://github.com/cloneofsimo/lora#mergigng-full-model-with-lora-and-changing-to-original-ckpt-format), which you can then use with A1111. 

Most of your question are answered in the README and @brian6091 great post under "Discussions": https://github.com/cloneofsimo/lora/discussions/37

**Comment by cloneofsimo** [comment]
I've closed this because this really has nothing to do with the repository. Concept of low-rank adaptation isn't mine. If you still have unanswered questions after going over @amerkay 's material, feel free to open another issue with question label.
