### ISSUE TITLE
Importing UnionType fails Python 3.8 (develop branch)

### ISSUE THREAD

**Issue by brian6091** [cloneofsimo/lora#78]
Just a heads-up that the develop branch will fail with python 3.8 (Google Colab version).

> ImportError: cannot import name 'UnionType' from 'types' (/usr/lib/python3.8/types.py)

Looks like this is new as of [python 3.10](https://docs.python.org/3/library/types.html).

@hafriedlander, any simple workaround?

**Comment by hafriedlander** [comment]
Ah, sorry, yeah, I only test in 3.10

Easiest fix is to replace any type that looks like `int | float` with `Union[int, float]`. Let me see if I can spot all the places I use that...

**Comment by hafriedlander** [comment]
Ah, bit more complicated. There's no easy fallback for `isinstance(object, UnionType)` - I'll have to rewrite that bit. 5 mins...

**Comment by brian6091** [comment]
Thank you on behalf of the plebs on Google Colab!

**Comment by brian6091** [comment]
One other problem,

You use 

> set(str)

to define default parameters, which will fail with (on Colab):

> TypeError                                 Traceback (most recent call last)
> 
> [<ipython-input-1-5acdbe2a1c36>](https://localhost:8080/#) in <module>
>       3 TEST = {"A", "B"}
>       4 def test(
> ----> 5     target_replace_module: set[str] = TEST,
>       6 ):
>       7     print(target_replace_module)
> 
> TypeError: 'type' object is not subscriptable

I avoided this by adding Set to the import:

> from typing import Callable, Dict, List, Optional, Tuple, Set

and replacing set(str) with Set(str). 

However, I have no idea whether this has the desired effect...

**Comment by hafriedlander** [comment]
Yeah, that'll work fine, they're equivalent. The lower-case-set syntax just avoids the import

**Comment by hafriedlander** [comment]
@brian6091 can you confirm if those change in PR #79 works in Colab?

**Comment by brian6091** [comment]
Looks like list[type[nn.Module]] should be List[type[nn.Module]]

> ---------------------------------------------------------------------------
> 
> TypeError                                 Traceback (most recent call last)
> 
> [<ipython-input-3-b939cf7f110b>](https://localhost:8080/#) in <module>
> ----> 1 from lora_diffusion import inject_trainable_lora
> 
> 1 frames
> 
> [/usr/local/lib/python3.8/dist-packages/lora_diffusion/lora.py](https://localhost:8080/#) in <module>
>      39 def _find_children(
>      40     model,
> ---> 41     search_class: list[type[nn.Module]] = [nn.Linear],
>      42 ):
>      43     """
> 
> TypeError: 'type' object is not subscriptable

**Comment by hafriedlander** [comment]
Hah, man. I guess I'll need to figure out how to run VS Code in Python 3.8 😳 . Fix for fix incoming...

**Comment by hafriedlander** [comment]
Looking like it's all the shortcut types (`tuple[]` and `type[]` too)

**Comment by hafriedlander** [comment]
Right, think I got them all..

**Comment by brian6091** [comment]
Everything imports cleanly. Thank you!

**Comment by hafriedlander** [comment]
@brian6091 we can close this one now, yeah?

**Comment by brian6091** [comment]
@hafriedlander Yes! Great work!
