### ISSUE TITLE
NameError: name 'hlip' is not defined

### ISSUE THREAD

**Issue by artyomnaz** [cloneofsimo/lora#85]
Hello!
Thanks you all for the amazing work! 
I got this error in 'lora/train_lora_dreambooth.py' by running Colab Example

![image](https://user-images.githubusercontent.com/47011391/209517021-f7180a2d-f86e-499f-8cae-6cf6d56d158a.png)

**Comment by wackywacko4** [comment]
Hello! I am getting the exact same issue. Any luck fixing it yet?

**Comment by cloneofsimo** [comment]
#86 should do the work. Sorry for not checking on these earlier
