### ISSUE TITLE
pt in automatic 1111

### ISSUE THREAD

**Issue by svumme** [cloneofsimo/lora#89]
I would like to know if is it  possible to use the files produced with lora on the automatic version 1111?

**Comment by DoughyInTheMiddle** [comment]
Directly no. I believe they're working on it.

Instead, you use the UI where on the upper right you select the ckpt file that you based the trained in the dropdown called "Model". In the one called "Lora Model", select the pt file that you want to use. Then click Generate CKPT and it will make a new CKPT file by merging them together.

**Comment by cloneofsimo** [comment]
There is extension by @d8hazard that let you use CLIP + Unet LoRAs. https://github.com/d8ahazard/sd_dreambooth_extension

**Comment by cloneofsimo** [comment]
I'm not so sure on the progress though. I am mainly working on methodologies, so I've provided minimal support at this point.
